### ISSUE TITLE
Request: /log clear

### ISSUE THREAD

**Issue by schoeke** [hannesm/jackline#103]
It would be nice to be able to clear the log and messaging window from within the client.

**Comment by hannesm** [comment]
there is `/clear` which clears the messaging window. the (possible, by default off) logging to disk cannot be removed from within the client (even `/log off` does not remove files), because I couldn't find any intuition/how it should be done by now (too many use cases, and various expectations, which lead me to the fact that the log file should be preserved, and manually removed).
