### ISSUE TITLE
block incoming messages from accounts not in roster

### ISSUE THREAD

**Issue by posiputt** [hannesm/jackline#163]
I am getting quite some spam lately, so this would be a nice little feature.

**Comment by hannesm** [comment]
(via a configuration option, do not block subscription requests (neither group messages) -- might conflict with #22, but that's why this should be an option)

**Comment by hannesm** [comment]
since 30 seconds, network events (presence or messages) will never (ever) create new contact items, but instead warnings are added to the status log... pls report if this is a fine solution for you, or you'd like additional massaging (such as a config option to silently drop all messages from unknown people)
