### ISSUE TITLE
Re connect loop 

### ISSUE THREAD

**Issue by lei6a** [hannesm/jackline#193]
Hi

since at least 2 day's my jackline end up in a Re- Connect loop 10 seconds after a succesfull connection with the error  

*async error * XMPP.Make(M)(XmlParser)(IDCallback).StreamError(_)
Output of  jackline -d true : 
[out.txt](https://github.com/hannesm/jackline/files/2178336/out.txt)

I testest the same jabber account with gajim and there was no problem, also testet a diffrent account (with no roaster) on the same server, with jackline and also no problem. So my best guess is that, as also the error message hints, while parsing the xml information witch come's with the roaster something breaks, but thats just a guess 
Some Information
uname -a:
Linux anon 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux
ocaml --version:
The OCaml toplevel, version 4.05.0

I did opam update && opam upgrade but the Error stayed

**Comment by infinity0** [comment]
If you are running jackline on two different devices simultaneously for the same XMPP account, make sure they have different XMPP/JID resources.

**Comment by hannesm** [comment]
dear @lei6a thanks for your report, as @infinity0 was commenting, from the out.txt it looks that the server closes the connection since there is already a connection with the same user account and resource.  could you check whether you have some other xmpp client with the same resource connecting there (you can login to xmpp multiple times with different resources, but only once with a single resource).

jackline could handle this issue more gracefully (rather than reconnecting), but I've had little time taking care of this recently.

**Comment by lei6a** [comment]
thx that was the case and closing that session resolved the problem. Yeah for me a sentence with in the documentation would have also done it, stating that this migth be a proble. Since at least for me its quit common that i sometimes forget that I already have a open session somewhere (I acctuly wondering why i did not stumble upon that earlyer). Again thanks for the quick response
