### ISSUE TITLE
failed assertion on Ctrl-Q

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#94]
on `HEAD is now at 6e211ba... deliver messages from the server (rather than failing) -- e.g. on initial connection to jabber.systemli.org`

This assertion just failed after pressing ctrl-q.
Ctrl-q worked previously in the same session, so for some reason there's some inconsistency in the state.

```
let active state =
  match Buddy.find_buddy state.users (Xjid.t_to_bare state.active_contact) with
  | None -> assert false
  | Some x -> x
```

Not sure what's going on there exactly.

**Comment by hannesm** [comment]
hmm... might be that there was a notification for `a@b/foo`, who logged out and `a@b/foo2` logged in? thus, `ctrl-q` tried to jump to `/foo`, but couldn't find them... need to guard the notification list from that (`foo` can be removed if `foo2` comes online because they are `similar` (a hack needed for libpurple))..

**Comment by hannesm** [comment]
also regressions of #74 occur again -- solution will be to have `` `Bare`` active, and use `active_session` for the session... then if active session changes from last communication (similar to `warn` if msg received from a different session than where to send to), warn the user... `` `Full`` should only be active if expanded and a concrete resource is selected..

**Comment by hannesm** [comment]
should be solved within https://github.com/hannesm/jackline/compare/d46bc09bee...432ee1e299
